name: CI

on:
  pull_request:
    branches: [ "main" ]   

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'    

    - name: Debug workspace (list files)
      run: ls -R
  
    - name: Restore dependencies
      run: dotnet restore ShaliShop.sln
      working-directory: ShaliShop

    - name: Build
      run: dotnet build ShaliShop.sln --no-restore --configuration Release
      working-directory: ShaliShop

    - name: Run tests
      run: |
        for proj in $(find src -name '*.Test.csproj' -o -name '*.Tests.csproj'); do
          echo "➡️ Running tests in $proj"
          dotnet test $proj --no-build --verbosity normal
        done
      working-directory: ShaliShop
