name: CI

on:
  pull_request:
    branches: [ "main" ]   

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'    

    - name: Debug workspace (list files)
      run: ls -R

    - name: Restore dependencies
      run: dotnet restore ShaliShop/ShaliShop.sln 

    - name: Build
      run: dotnet build ShaliShop/ShaliShop.sln  --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ShaliShop/ShaliShop.sln  --no-build --verbosity normal
